
[build]
  command = "npm run build"
  publish = ".next"

# Use the official Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["openai", "sharp"]
  node_bundler = "esbuild"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
