[build]
  command = "npm run build"
  publish = ".next"

# Essential for Next.js API routes on Netlify
[functions]
  directory = ".netlify/functions"
  external_node_modules = ["openai"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
