
[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

# Use the official Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"


[functions]
  external_node_modules = ["openai"]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200




[build.environment]
  NODE_VERSION = "18"
