[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'Backend API server - no build step required'"]

[start]
cmd = "node index.js"

[staticAssets]
# Disable static asset serving - this is an API server
enabled = false
